language: objective-c
osx_image: xcode10.1
install: true

jdk:
  - oraclejdk8

before_install:
  - brew tap caskroom/cask
  - brew cask install android-sdk

script:
  - ./gradlew :core-multiplatform:build --configure-on-demand --info
