os: osx
osx_image: xcode10.1
language: android

before_install:
  - pod repo update --silent
  - gem install xcpretty
  - brew cask install homebrew/cask-versions/java8
  - export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

install:
  - cd iosApp
  - pod install
  - cd ..

script:
  - ./gradlew :core-multiplatform:build --configure-on-demand
  - cd core-multiplatform
  - cd build
  - ls
  - cd ..
  - cd ..
  - cd iosApp
  - swiftlint
  - set -o pipefail && xcodebuild -workspace iosApp.xcworkspace -scheme 'iosApp' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/